name: igyal2
description: "Igyal 2 - party drinking game"
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ^3.11.5
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  http: ^1.2.0
  meta: ^1.17.0
  path_provider: ^2.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/content/tasks.json
